Repository dyc3/opentogethertube, pull requests merged in 2019-11, with the labels that each got.

#146 mock axios requests so tests don't hit the real youtube API
  infoextract.js
  tests/unit/infoextractor.spec.js
Labels: refactor, server

#149 fix youtu.be urls not working in add previews
  infoextract.js
Labels: bug, server, youtube

#150 Placeholder image does not appear in firefox
  src/views/RoomList.vue
Labels: bug, client

#151 Disable seeker slider when no video is loaded.
  src/views/Room.vue
  tests/unit/room.spec.js
Labels: bug, client
