Repository dyc3/opentogethertube, pull requests merged in 2019-09, with the labels that each got.

#46 auto create the db folder if it doesn't exist
  config/config.js
Labels: enhancement

#28 Fix db config for production deployment
  config/config.js
Labels: enhancement, server

#29 Refactor getVideoInfoYoutube
  infoextract.js
  roommanager.js
Labels: refactor, server

#56 add meta description tag fix #26
  public/index.html
Labels: enhancement

#55 fix websockets connecting on ssl
  src/views/Room.vue
Labels: bug, client

#59 update styles and colors to improve readability
  src/plugins/vuetify.js
  src/views/Room.vue
Labels: client

#60 youtube player immediately begins loading fixes #38
  src/views/Room.vue
Labels: bug, client

#57 Display number of videos in queue
  src/views/Room.vue
Labels: client, enhancement

#61 Add Windows support with npm script
  package.json
Labels: dependencies, enhancement

#67 Add Travis CI config
  .eslintrc.js
  .travis.yml
  README.md
  package-lock.json
  package.json
  roommanager.js
  tests/unit/example.spec.js
Labels: enhancement

#71 More defined eslint rules
  .eslintrc.js
  api.js
  app.js
  babel.config.js
  config/config.js
  infoextract.js
  jest.config.js
  migrations/20190830172621-create-room.js
  models/index.js
  models/room.js
  package.json
  postcss.config.js
  roommanager.js
  src/.eslintrc.js
  src/common-http.js
  src/main.js
  src/plugins/vuetify.js
  src/router.js
  src/store.js
  storage.js
  vue.config.js
Labels: enhancement, refactor

#66 Added timestamp for current video playing
  src/timestamp.js
  src/views/Room.vue
Labels: client, enhancement

#70 Removed add button
  src/views/Room.vue
Labels: client, enhancement

#64 queue endpoint supports service and id parameters, closes #63
  api.js
  roommanager.js
Labels: enhancement, server

#78 fix implementation of v-tabs component
  src/views/Room.vue
Labels: bug, client

#74 Removed whitespace in script causing missing file errors
  package.json
Labels: bug

#81 Fix vue linting
  .travis.yml
  package.json
  src/App.vue
  src/components/VideoQueueItem.vue
  src/views/Home.vue
  src/views/Room.vue
  src/views/RoomList.vue
Labels: bug

#85 fix linting scripts again :(
  package.json
Labels: refactor

#88 Improved mobile version of landing page
  src/views/Home.vue
Labels: client, enhancement

#91 Rewrite temporary room with moment
  roommanager.js
Labels: refactor

#77 replaced playbackDuration with currentSource.length where appropriate
  roommanager.js
  src/store.js
  src/views/Room.vue
Labels: refactor

#84 Add local cache for video metadata
  .travis.yml
  config/config.js
  infoextract.js
  migrations/20190921194802-create-cached-video.js
  models/cachedvideo.js
  roommanager.js
  storage.js
  tests/unit/infoextractor.spec.js
  tests/unit/storage.spec.js
Labels: enhancement, server

#87 Show buttons only when in development mode
  src/store.js
  src/views/Room.vue
Labels: client, enhancement

#90 Redesign VideoQueueItem
  src/components/VideoQueueItem.vue
Labels: bug, client, enhancement

#86 fix crash when sending sync to closed socket
  roommanager.js
Labels: bug, server
