Repository dyc3/opentogethertube, pull requests merged in 2019-12, with the labels that each got.

#152 Validate youtube video ids before using them
  api.js
  infoextract.js
Labels: bug, server

#155 Uses 'default' method of retrieval for private vid
  infoextract.js
Labels: bug, server

#153 Added a message and Create Room button in case no rooms exist on the page.
  src/views/RoomList.vue
Labels: client, enhancement

#154 Created "Add All Videos in Playlist to Queue" Button
  src/views/Room.vue
Labels: client, enhancement

#158 Private rooms
  api.js
  migrations/20191210180250-add-visibility-to-rooms.js
  roommanager.js
  storage.js
Labels: enhancement, server

#159 Drag and drop video queue
  package-lock.json
  package.json
  roommanager.js
  src/components/VideoQueueItem.vue
  src/views/Room.vue
Labels: enhancement

#160 Rooms must have unique names
  api.js
  roommanager.js
  tests/unit/roommanager.spec.js
Labels: bug, server

#162 Sanitize room names on creation
  api.js
Labels: bug

#164 Show loading indicator for add previews and error messages when they fail
  api.js
  infoextract.js
  src/views/Room.vue
Labels: client, enhancement, server

#173 User sessions
  api.js
  app.js
  package-lock.json
  package.json
  roommanager.js
  src/store.js
  src/views/Room.vue
Labels: client, enhancement, server
