Repository dyc3/opentogethertube, pull requests merged in 2019-10, with the labels that each got.

#80 Error handling when getting room from database
  roommanager.js
  storage.js
Labels: bug, server

#82 Added more eslint styles to enforce code styling
  .eslintrc.js
  package-lock.json
  package.json
  src/plugins/vuetify.js
  src/timestamp.js
Labels: refactor

#114 Adds logo and other misc assets. Closes #16
  public/favicon.ico
  src/App.vue
  src/assets/logo.png
  src/assets/logo.svg
  src/assets/placeholder.svg
Labels: enhancement

#89 Added support for youtube channels
  infoextract.js
Labels: enhancement, server

#94 Cancel temp room
  src/views/Home.vue
Labels: client, enhancement

#107 Make VideoQueueItem feel a little more responsive
  src/components/VideoQueueItem.vue
Labels: client, enhancement

#116 Make slider bubble contain timestamp instead of time in seconds.
  src/views/Room.vue
Labels: bug, client

#109 add nanotimer, fixes #33 by providing more accurate setInterval
  package-lock.json
  package.json
  roommanager.js
Labels: bug, server

#103 Add lots of tests for back end
  infoextract.js
  roommanager.js
  storage.js
  tests/unit/infoextractor.spec.js
  tests/unit/roommanager.spec.js
  tests/unit/storage.spec.js
Labels: enhancement

#112 Add tests for room view and code coverage report
  .gitignore
  jest.config.js
  src/store.js
  src/views/Room.vue
  tests/unit/room.spec.js
Labels: enhancement

#111 add keyboard bind to control playback, similar to youtube
  src/views/Room.vue
Labels: client, enhancement

#119 Better room manager
  api.js
  app.js
  package-lock.json
  roommanager.js
  tests/unit/roommanager.spec.js
Labels: refactor, server

#121 add "not found" page
  src/router.js
  src/views/NotFound.vue
Labels: bug, client

#117 Change VideoQueueItem to row/column dynamic layout
  package-lock.json
  src/components/VideoQueueItem.vue
Labels: bug, client, refactor

#123 Fullscreen mode
  src/App.vue
  src/views/Room.vue
Labels: client, enhancement

#128 clean up random stuff
  src/components/VideoQueueItem.vue
  src/router.js
  src/views/Room.vue
Labels: client, refactor

#126 edit username text box now updates correctly
  src/views/Room.vue
Labels: bug, client

#127 fix loading indicators not showing for VideoQueueItem
  src/components/VideoQueueItem.vue
Labels: bug, client

#122 refactor room to use v-row and v-col, and use more screen space
  src/views/Room.vue
Labels: client, refactor

#130 fix #124
  src/views/RoomList.vue
Labels: bug, client

#137 Clean up commented code
  roommanager.js
Labels: refactor

#132 Chat
  roommanager.js
  src/store.js
  src/views/Room.vue
Labels: client, enhancement, server

#134 dirty fix for null usernames on first visit
  src/views/Room.vue
Labels: bug, client

#136 Better room cards
  src/views/RoomList.vue
Labels: client, enhancement

#141 Disable autocomplete on chat text box
  src/views/Room.vue
Labels: bug, client

#125 make onInputAddChange() run without needing to defocus the text box
  src/views/Room.vue
Labels: bug, client

#145 Added tests to ensure proper functionality of unloading rooms with no active users
  roommanager.js
  tests/unit/roommanager.spec.js
Labels: enhancement, server
