Repository dyc3/opentogethertube, pull requests merged in 2020-10, with the labels that each got.

#307 ridiculous hack to fix #300 while keeping #290 fixed
  roommanager.js
  src/store.js
  src/views/Room.vue
Labels: bug, client

#309 better eslint
  .eslintrc.js
  infoextract.js
  logger.js
  roommanager.js
  src/.eslintrc.js
  src/components/ProcessedText.vue
  src/store.js
  src/views/Room.vue
Labels: refactor

#314 enter key submits form
  src/components/LogInForm.vue
Labels: client, enhancement
