Repository dyc3/opentogethertube, pull requests merged in 2020-08, with the labels that each got.

#279 Test refactoring
  .eslintrc.js
  roommanager.js
  tests/unit/server/infoextractor.spec.js
  tests/unit/server/roommanager.spec.js
  tests/unit/server/storage.spec.js
Labels: refactor, tests

#282 Extract video player into its own component
  src/components/DailymotionPlayer.vue
  src/components/OmniPlayer.vue
  src/components/VimeoPlayer.vue
  src/views/Room.vue
Labels: client, refactor

#283 Extract chat into its own component
  src/components/Chat.vue
  src/views/Room.vue
Labels: client, refactor

#286 Config validation
  app.js
Labels: enhancement, server

#288 Add all refactor
  api.js
  roommanager.js
  src/store.js
  src/views/Room.vue
Labels: bug, client, refactor, server
