Repository dyc3/opentogethertube, pull requests merged in 2020-02, with the labels that each got.

#184 Change message on the add video entry field
  src/views/Room.vue
Labels: enhancement

#187 Vimeo support
  infoextract.js
  package-lock.json
  package.json
  roommanager.js
  src/components/VimeoPlayer.vue
  src/views/Room.vue
  tests/unit/infoextractor.spec.js
  tests/unit/room.spec.js
Labels: enhancement

#188 fix parsing short youtube urls with query params
  infoextract.js
  tests/unit/infoextractor.spec.js
Labels: enhancement, server

#192 Voting mode
  api.js
  roommanager.js
  src/components/VideoQueueItem.vue
  src/store.js
  src/views/Room.vue
Labels: client, enhancement, server

#195 Redis
  README.md
  app.js
  package-lock.json
  package.json
  roommanager.js
Labels: enhancement, server
