Repository dyc3/opentogethertube, pull requests merged in 2024-02, with the labels that each got.

#1322 upgrade vuetify
  client/package.json
  yarn.lock
Labels: dependencies

#1356 switch `ott-server` to import `ott-common` instead of referencing the relative file path
  server/admin.ts
  server/api/announce.ts
  server/api/data.ts
  server/api/dev.ts
  server/api/room.ts
  server/auth/index.ts
  server/auth/tokens.ts
  server/balancer.ts
  server/client.ts
  server/clientmanager.ts
  server/exceptions.ts
  server/express-types.d.ts
  server/infoextractor.ts
  server/mailer.ts
  server/models/cachedvideo.ts
  server/models/room.ts
  server/ott-config.ts
  server/room.ts
  server/roommanager.ts
  server/serviceadapter.ts
  server/services/dailymotion.ts
  server/services/dash.ts
  server/services/direct.ts
  server/services/googledrive.ts
  server/services/hls.ts
  server/services/peertube.ts
  server/services/pluto.ts
  server/services/reddit.ts
  server/services/tubi.ts
  server/services/vimeo.ts
  server/services/youtube.ts
  server/storage/cachedvideo.ts
  server/storage/room.ts
  server/tests/unit/api/accountrecovery.spec.ts
  server/tests/unit/api/announcement.spec.ts
  server/tests/unit/api/room.spec.ts
  server/tests/unit/api/user.spec.ts
  server/tests/unit/clientmanager.spec.ts
  server/tests/unit/infoextractor.spec.ts
  server/tests/unit/room.spec.ts
  server/tests/unit/roommanager.spec.ts
  server/tests/unit/services/youtube.spec.ts
  server/tests/unit/storage.spec.ts
  server/usermanager.ts
  server/videoqueue.ts
  server/vitest.config.ts
  tests/e2e/integration/room-settings.spec.ts
Labels: refactor

#1317 balancer: add a command line argument to validate config
  crates/ott-balancer/src/config.rs
  crates/ott-balancer/src/lib.rs
Labels: balancer

#1271 add test for malformed websocket
  Cargo.lock
  crates/harness-tests/Cargo.toml
  crates/harness-tests/src/routing.rs
  crates/harness/src/test_runner.rs
Labels: balancer

#1395 add retry to flaky test
  server/tests/unit/storage.spec.ts
Labels: tests

#1415 collector: reorganize imports, add derives to `SystemState` and others
  crates/ott-collector/Cargo.toml
  crates/ott-collector/src/main.rs
Labels: refactor
